[package]
name = "rune-ensemble"
version = "0.1.0"
authors = ["Jack <admin@deadcore.co.uk>"]
edition = "2018"
workspace = "../.."

[features]
default = []

[lib]
name = "rune_ensemble"

[dependencies]
log = "^0.4"
ndarray = "^0.13"
ndarray-rand="^0.11"
ndarray-csv = "^0.4"